### ISSUE TITLE
cbuild: not found

### ISSUE THREAD

**Issue by imxade** [chimera-linux/cports#100]
```sh
strace --failed-only ./bootstrap.sh
```
```sh
/bootstrap-inner.sh: 23: ./cbuild: not found
ioctl(2, TIOCGWINSZ, 0x7fffaf77a600)    = -1 ENOTTY (Inappropriate ioctl for device)
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=299, si_uid=0, si_status=127, si_utime=0, si_stime=0} ---
wait4(-1, 0x7fffaf779f50, WNOHANG, NULL) = -1 ECHILD (No child processes)
Bootstrap failed!
```

**Comment by q66** [comment]
this is not enough information, there is no reason for that to happen and as far as i can tell never did before

describe your setup and complete process

**Comment by imxade** [comment]
> this is not enough information, there is no reason for that to happen and as far as i can tell never did before
> 
> describe your setup and complete process

Sorry, for such a casual behavior should've done that earlier

I ran the script on gitlab CI/CD pipeline
image : artixlinux/base

here are the exact commands

```sh
pacman -Sy --noconfirm --needed tar xz gzip zstd gawk curl util-linux git bubblewrap strace
curl -OL https://raw.githubusercontent.com/chimera-linux/cports/master/bootstrap.sh
chmod +x ./bootstrap.sh 
strace --failed-only ./bootstrap.sh
```

**Comment by q66** [comment]
that means you haven't read the usage documentation, this is not how cports is used
