### ISSUE TITLE
Add gnome-software

### ISSUE THREAD

**Issue by AsciiWolf** [chimera-linux/cports#101]
Please, consider supporting GNOME Software if possible or similar GUI tool to manage packages/ports (+ additional package formats like Flatpaks) in Chimera Linux. It would make the distro more accessible to many new users.

**Comment by q66** [comment]
isn't gnome-software a frontend for specific packaging systems? i don't think that is really supported in upstream right now

also, considering the distro is in early stage development such requests are a bit early and out of place

**Comment by AsciiWolf** [comment]
It is. Anyway, it could be used at least for Flatpaks (only the Flatpak plugin enabled). But I guess you're right about the early stage of development. Sorry. It was more a suggestion than a request.

**Comment by q66** [comment]
in order to have that one needs to have flatpak itself first and that's not really there either right now (though it will be eventually, it's a little tricky in some ways, e.g. gonna have to patch out dependency on elfutils)
