### ISSUE TITLE
Explicit updating local-compiled packages from the official repos

### ISSUE THREAD

**Issue by mobin-2008** [chimera-linux/cports#1012]
Hi. there is explicit way to update a local-compiled from the official repos regardless of its version?

**Comment by q66** [comment]
i have no idea what you mean by this

**Comment by JamiKettunen** [comment]
I suppose you mean https://github.com/chimera-linux/cports#pinning-the-repositories, couldn't you do the following if the local repo is indeed tagged (e.g. as `cports`)?  `apk del linux-stable@cports && apk add linux-stable`

**Comment by sidkshatriya** [comment]
To make the process even more explicit:
```
$ cd /etc/apk/repositories.d
$ doas su
# cat > 999-repo-local.list <<EOT
> @cports /home/abcxz/cports/packages/main
> @cports /home/abcxyz/cports/packages/main/debug
> EOT
# edit
```
Here the assumption is that you have cloned the cports repo into `/home/abcxyz/cports`

**Comment by mobin-2008** [comment]
Thank you guys, My problem was that I installed many packages manually (via `apk add ./package.apk`) and they weren't marked from `@cports`. I modified apk's world and mark every packages which are from my local repo as `@cports`.

I close this issue.
