### ISSUE TITLE
catch-22 if apk-tools isn't pre-installed

### ISSUE THREAD

**Issue by subnut** [chimera-linux/cports#103]
If `apk-tools` isn't installed, then `cbuild keygen` fails (because it can't find `apk`).

If we try to use `bootstrap.sh` to obtain a rootdir containing `apk`, then that doesn't work either. `bootstrap-inner.sh` fails at the final step (`cbuild bootstrap`) with the error -
```
=> cbuild: no signing key set
```

So, we can't create a key without `apk`, nor can we successfully bootstrap to obtain `apk`.

**Comment by q66** [comment]
i don't see an issue, the docs clearly state apk-tools must be present in the host system
