### ISSUE TITLE
xinit rewrite for xorg-based setups

### ISSUE THREAD

**Issue by q66** [chimera-linux/cports#109]
The `xinit` scripts as they ship upstream are a huge mess and do not work well with our service management (e.g. when launching a desktop with `startx`, the dbus session bus address is not exported into the desktop session). We will probably want to just rewrite all the scripts to play nice with `dinit`.

**Comment by ifreund** [comment]
The `sx` projects might be useful as an alternative or a good starting point for writing a chimera-specific one: https://github.com/Earnestly/sx

**Comment by q66** [comment]
i actually had something entirely different in mind, I'd like to turn the xorg session startup into a user service, that way it will run under supervision and inherit the entire activation environment

but I haven't thought about details much yet

**Comment by q66** [comment]
implementing as a service is actually not possible because with rootless xorg one needs to use the current tty, while services are inherently detached from tty's

so i ended up implementing a somewhat different system, which still addresses our problems
