### ISSUE TITLE
libgcc compatibility shim

### ISSUE THREAD

**Issue by q66** [chimera-linux/cports#112]
We use `compiler-rt` as the system runtime, but for existing binaries we might want to provide a shim library that would enable gcc-compiled executables to run. This would also enable having `gcc` in `contrib` later. Right now we can't because GCC is not capable of targeting our system runtime.

**Comment by q66** [comment]
the alpha will ship with llvm 15, and while that comes with the new llvm-libgcc stuff, it's clearly not fit for our purpose and therefore i will not be including it

**Comment by RoastVeg** [comment]
Out of curiosity, exactly how deficient is llvm-libgcc? I'm aware that the symbols in it are only what's already present in compiler-rt/libunwind, but is there a metric on how far off it is?

**Comment by q66** [comment]
it's defined for a very limited set of targets (currently just a few x86+arm ones) with a manually generated symbol version list + the way it's set up means it's not a compatibility shim per se but instead *replaces* the compiler-rt for everything

**Comment by q66** [comment]
should be sufficiently addressed by https://github.com/chimera-linux/cports/commit/07e109a0ee9a2e97ffbe30766224e0e67afbbb4f

i will move it to contrib once better tested
