### ISSUE TITLE
Remove readline or move it to contrib

### ISSUE THREAD

**Issue by q66** [chimera-linux/cports#116]
We are using `libedit` as a replacement in most users but there are some notable cases currently using `readline` in ways the `libedit` API does not yet cover:

* `iwd`
* `bluez`
* `parted`

We should either improve `libedit` to enable these, or address the issues in a different way.

May not be necessary for the alpha milestone but tagging it anyway for now.

**Comment by RoastVeg** [comment]
Looks like the next release (and current master) `iwd` has libedit support now

**Comment by q66** [comment]
except it doesn't, it adds a configure option but does zero work to make it function properly (which it won't, because libedit does not have non-stub support for redisplay hooks and so on yet)
