### ISSUE TITLE
Settings icon missing in GNOME Settings titlebar

### ISSUE THREAD

**Issue by mhmdanas** [chimera-linux/cports#1225]
![Screenshot of GNOME's Settings app, with a placeholder icon on the left of the title bar](https://github.com/chimera-linux/cports/assets/32234660/cecc9b23-5b88-453c-8e2f-3f664a52e51e)

**Comment by q66** [comment]
i don't think there's supposed to be an icon, and there isn't here
![Screenshot from 2024-01-12 21-47-15](https://github.com/chimera-linux/cports/assets/222373/9ccfbb67-5ee2-48dd-bf0d-c2e50b9a527c)

**Comment by q66** [comment]
you probably have some weird tweaked gtk settings that force an icon to appear where it shouldn't be

**Comment by mhmdanas** [comment]
I asked in `#gnome:gnome.org`, and with their help I figured out that `gsettings set org.gnome.desktop.wm.preferences button-layout appmenu:minimize,maximize,close` fixes it (it was `menu` instead of `appmenu` before).
