### ISSUE TITLE
Consider rust coreutils rather than chimerautils for better compatibility

### ISSUE THREAD

**Issue by sidkshatriya** [chimera-linux/cports#1280]
In cports I notice a lot of patches to solve some minor incompatibility chimerautils has e.g. use of short flag name, different flag, slightly different behavior in the tool (e.g. `dd` is slightly different) etc. etc.

I understand why we don't want to use GNU coreutils. Have we considered https://github.com/uutils/coreutils which is written in rust and tries to be fully compatible with GNU coreutils ?

**Comment by RoastVeg** [comment]
AFAIU, one of the goals for chimera-linux is to be bootstrappable from source pretty quickly. The `base-minimal` package currently doesn't pull in any Rust dependencies, and therefore no rustc, which is pretty complex to bootstrap.

**Comment by sidkshatriya** [comment]
Good points. I'm inclined to agree. 

However, not having full compatibility with coreutils means a lot of time is spend solving these compatibility issues which means that packages are added slowly to chimera.

Is bootstrapping rust such a big problem ? After all we do use llvm/clang which is different from other distributions that use gcc as their primary compiler. Going from llvm/clang to rust might be less of a problem ? Perhaps this is still too massive of a dependency ?

**Comment by q66** [comment]
i don't care about gnu coreutils compatibility, it's fundamentally an anti-feature and anybody who suggests transitioning to something else because it would make things "easier" is 100% missing the point

besides, coreutils compatibility is not an obstacle for adding packages like, pretty much ever

**Comment by RoastVeg** [comment]
> Is bootstrapping rust such a big problem ? After all we do use llvm/clang which is different from other distributions that use gcc as their primary compiler. Going from llvm/clang to rust might be less of a problem ? Perhaps this is still too massive of a dependency ?

The bootstrapping effort is actually a little more involved in Chimera over other distros, since Chimera carries patches to use the system LLVM, as well as a custom target that dynamically links the system musl libc.
