### ISSUE TITLE
GNOME Web (epiphany) - WebkitProcess crashes

### ISSUE THREAD

**Issue by runlevel5** [chimera-linux/cports#130]
## System Info

System: Raptor Blackbird
Kernel: 6.0.2-generic ppc64le
GNOME Web version: 43.0-r0

## Steps to reproduce:

* Open GNOME Web
* Enter `https://google.com`

### Expected

Google page loaded up

### Actual

Blank screen. The console says:

```
(process: 2) WARNING **: <timestamp> - Failed to connect to bus: Could not connect: No such file or directory
```

Please note dbus daemon is running, I could confirm with `dinitctl status dbus`

**Comment by q66** [comment]
you probably don't have the *session* bus running (i.e. the dbus **user** service is not up)

**Comment by q66** [comment]
enable the dinit-userservd system service, log out your user, log in again, `dinitctl enable dbus` as your user, log out again, log in again, and that should be it
