### ISSUE TITLE
Current version of main/grub does not work with XFS filesystems created using default options.

### ISSUE THREAD

**Issue by Ferroin** [chimera-linux/cports#1309]
When attempting to run `grub-install` when `/boot` is an XFS volume formatted using `mkfs.xfs` without any additional options, GRUB fails to install with an error message about an unrecognized filesystem.

I discovered this when setting up a couple of VMs, and with a bit of testing have localized the issue to the `nrext64` inode option. Using a volume formatted using `mkfs.xfs -i nrext64=0` works without issue.

From some further investigation on other systems, it looks like GRUB 2.12 has no issues with this, so there’s presumably a patch somewhere that could be applied if a version bump is not desirable for some reason.

**Comment by nekopsykose** [comment]
it'll be updated at some point, just needs some time/testing :)
