### ISSUE TITLE
contrib/slirp4netns: crashes with 'invalid opcode'

### ISSUE THREAD

**Issue by flukeeey** [chimera-linux/cports#1400]
When using podman containers, the packaged version of slirp4netns crashes after a few minutes, with the following errors in klog:

`traps: slirp4netns[22557] trap invalid opcode ip:5601a49b306a sp:7ffd72f682a0 error:0 in slirp4netns[5601a49b0000+9000]`

This kills networking in my containers until I restart them and relaunch slirp4netns (only for it to crash again a few mins later).

Setting `!cfi` in package options fixes the problem and slirp4netns becomes stable again.

**Comment by nekopsykose** [comment]
i tried reproducing this a while ago but could never get it to actually happen, what do you run?

**Comment by q66** [comment]
can you grab a core and check the backtrace?
