### ISSUE TITLE
YT video playback issues in both Firefox & GNOME Web

### ISSUE THREAD

**Issue by JamiKettunen** [chimera-linux/cports#144]
Trying to playback any video in Firefox will crash the tab process (`Isolated Web Content`) typically in under a minute with this left in `dmesg`:
```
traps: Isolated Web Co[7868] trap invalid opcode ip:7fad223b5600 sp:7ffe4f921f58 error:0 in libxul.so[7fad1e149000+56f0000]
```
Attempting the same in GNOME Web it crashes even before the video playback is started / the page finished loading fully:
```
traps: qtdemux1:sink[8906] trap invalid opcode ip:7fca6640046c sp:7fca66a31838 error:0 in libfdk-aac.so.2.0.2[7fca662fe000+123000
```

**Comment by q66** [comment]
as far as i know this is not a problem anymore? at least in firefox it will not crash, and epiphany appears to work for me too

**Comment by JamiKettunen** [comment]
I can check tomorrow how it works with ~10 minute videos on each, I'll close this if I can't reproduce on a `apk upgrade -a`'d bare metal :)
