### ISSUE TITLE
podman: complains that `/` is not a shared mount

### ISSUE THREAD

**Issue by sidkshatriya** [chimera-linux/cports#1528]
When I try to `podman pull` I get the following cryptic error:

```
WARN[0000] "/" is not a shared mount, this could cause issues or missing mounts with rootless containers
```

Searching on the net, a possible way to address might be to `mount --make-shared /` or `mount --make-rshared /`. I'm not sure if this is the best way to go about this or just live with the warning.

`/` is currently set as a private mount.

 I have not encountered this warning on other distributions so I wanted any suggestions / advice on addressing this on chimera.

**Comment by nekopsykose** [comment]
https://gitlab.alpinelinux.org/alpine/aports/-/issues/13565 summarises most of it. basically when --make-shared it backpropagates mounts or somesuch

you can put `mount --make-shared /` in `/etc/rc.local`. but maybe we should make it the default.. i'm not sure what downsides there are (systemd does it by default)
