### ISSUE TITLE
main/networkmanager/NetworkManager.conf: file name clash due to macOS case insensitivity causes problems

### ISSUE THREAD

**Issue by sidkshatriya** [chimera-linux/cports#1530]
The commit cbcedb82e70b9f97a227c8610d8ac669adba2b18 ( cc: @q66 ) seems to be causing problems when you try to clone the github `cports` repository on macOS. The problem arises to the case insensitivity of the file system on macOS. 

```
# On macOS
$ git clone https://github.com/chimera-linux/cports.git
Cloning into 'cports'...
remote: Enumerating objects: 72796, done.
remote: Counting objects: 100% (72796/72796), done.
remote: Compressing objects: 100% (27066/27066), done.
remote: Total 72796 (delta 38480), reused 72478 (delta 38388), pack-reused 0
Receiving objects: 100% (72796/72796), 16.46 MiB | 5.77 MiB/s, done.
Resolving deltas: 100% (38480/38480), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'main/networkmanager/files/NetworkManager.conf'
  'main/networkmanager/files/networkmanager.conf'
```

Look at `main/networkmanager/files` -- you will notice that there are 2 files
- `networkmanager.conf`
- `NetworkManager.conf`

**Firstly, I think this is a mistake, there probably should be only 1 file ?** 

On linux these are treated as different files (as they should). On macOS, git gets confused between the two files.

**Comment by nekopsykose** [comment]
> Firstly, I think this is a mistake, there probably should be only 1 file ?  

no, one is the config and the other is tmpfiles  

doesn't look like a bug. not hard to fix but caring about non-conflicting on casefolded filesystems is annoying

**Comment by nekopsykose** [comment]
you can create a case-sensitive apfs volume to put cports on
