### ISSUE TITLE
-fno-omit-frame-pointer, -Cforce-frame-pointers=yes

### ISSUE THREAD

**Issue by nekopsykose** [chimera-linux/cports#1604]
arch, fedora, and ubuntu now started doing this, so maybe we should too

long discussion (in arch): https://gitlab.archlinux.org/archlinux/rfcs/-/merge_requests/26  
some implementation notes: https://gitlab.archlinux.org/daandemeyer/rfcs/-/blob/fp/rfcs/0026-fno-omit-frame-pointer.rst  

tl;dr: profiling stuff using dwarf backtraces is often quite unreasonable, https://rwmj.wordpress.com/2023/02/14/frame-pointers-vs-dwarf-my-verdict/ is quite funny. having fp enabled makes it much easier to 'get an accurate flamegraph of why something is slow', quickly, and with low overhead. manually rebuilding stuff with fp locally is usually far too much hassle  

misc other info: https://www.brendangregg.com/blog/2024-03-17/the-return-of-the-frame-pointers.html

overall performance loss is dependent on package and the worst offenders seem to be '10%' for things like python- and that's only in synthetic benches. we could leave a per-package optout too. in general it seems the effect is not noticeable

**Comment by sidkshatriya** [comment]
Yes, I too think we should default to having the frame pointer used to point to the frame rather than used as a normal register.

> misc other info: https://www.brendangregg.com/blog/2024-03-17/the-return-of-the-frame-pointers.html

This article sums it up well
