### ISSUE TITLE
X11 GNOME broken on accelerated GPU drivers

### ISSUE THREAD

**Issue by JamiKettunen** [chimera-linux/cports#184]
Upon launching GNOME on Xorg from GDM for example on my RX 6600 pointer follows mouse movement but the desktop rendering itself doesn't go further than a single frame which can be advanced by switching to another TTY and back again to get the next one.

A workaround may be the following as `/usr/share/X11/xorg.conf.d/99-kms-no-pageflip.conf` for example:
```
Section "Device"
       Identifier "kms"
       Driver "modesetting"
       Option "PageFlip" "off"
EndSection
```
Keep in mind this may cause problems such as screen tearing etc.

Reportedly @q66 also tested Enlightenment (X11) **without** the above workaround and it worked fine.

Upstream report: https://gitlab.freedesktop.org/mesa/mesa/-/issues/9152

**Comment by q66** [comment]
This will probably be wontfix, it seems Fedora might drop X11 session support in GNOME relatively soon (https://www.phoronix.com/news/Fedora-40-Eyes-No-X11-Session) which means it should become possible in upstream to disable it - Chimera will probably follow suit here shortly (AFAICT there is practically no benefit to running X11 GNOME)

**Comment by q66** [comment]
well, i just tried it again and... it wroks for me now?

**Comment by q66** [comment]
@nekopsykose confirmed this also works on amd, so i guess it's fine now
