### ISSUE TITLE
Wrap linux64 error message into something nicer

### ISSUE THREAD

**Issue by ptrcnull** [chimera-linux/cports#1889]
when an executable is missing, linux64 just prints:
```
linux64: execvp: No such file or directory
```

it could be wrapped with more context from the calling function, so the user doesn't have to read through the stack trace and long `bwrap ...` command to check the actual missing thing

**Comment by q66** [comment]
i could not figure out a satisfactory way to wrap this, but i made the linux64 binary itself print something more useful, so now you get something like

```
=> libass-0.17.1-r1: running do_configure...
linux64: execvp: failed to execute 'autoreconf': No such file or directory
```

which should be a lot less confusing?
