### ISSUE TITLE
[Request] add netbsd-curses

### ISSUE THREAD

**Issue by xplshn** [chimera-linux/cports#1917]
This is [netBSD-curses](https://github.com/sabotage-linux/netbsd-curses), which can be used to build lots of ncurses packages faster, and also reduces binary size and complexity. I'd like to see it included, it really is awesome given how compatible it is, personally, I never had problems with it, even building complex programs with it works fine.

NOTE: I didn't know where to request packages. Maybe they simply aren't allowed? IDK.

**Comment by q66** [comment]
given no really active port of netbsd-curses, no mouse support, and subpar single-file handling of terminfo database that is incompatible with most software using `tic`, i have no plans to introduce that

**Comment by xplshn** [comment]
Seems fair, however, I didn't ask for it to come installed by default
