### ISSUE TITLE
protoc should depend on protobuf-devel

### ISSUE THREAD

**Issue by valpackett** [chimera-linux/cports#1987]
(or i guess the `usr/include/google/protobuf/*.proto` stuff should be a separate package that both protobuf-devel and protoc depend on)

or we just randomly get stuff like…

```
error: failed to run custom build command for `atuin-daemon v0.1.0 (/home/val/src/github.com/atuinsh/atuin/crates/atuin-daemon)`

Caused by:
  process didn't exit successfully: `/home/val/src/github.com/atuinsh/atuin/target/release/build/atuin-daemon-8c35c4897a698ae8/build-script-build` (exit status: 1)
  --- stdout
  cargo:rerun-if-changed=./proto/history.proto
  cargo:rerun-if-changed=./proto

  --- stderr
  Error: Custom { kind: Other, error: "protoc failed: google/protobuf/timestamp.proto: File not found.\nhistory.proto:4:1: Import \"google/protobuf/timestamp.proto\" was not found or had errors.\n" }
```

because nothing expects a system-wide protoc to exist without these default `.proto` files

**Comment by nekopsykose** [comment]
seems fine to make it depend on -devel

**Comment by q66** [comment]
ftr the main reason this wasn't done was because of crosscompiling (with the dep added protoc pointlessly pulls in -devel on the host and its dep tree)

though idk how much it actually matters in the end

**Comment by nekopsykose** [comment]
i could make *.proto a separate thing to get around it but i'm also not sure what the loss is in pulling the tree, shrug
