### ISSUE TITLE
bubblejail missing and incorrect dependencies

### ISSUE THREAD

**Issue by igo95862** [chimera-linux/cports#2015]
Hello,

I am bubblejail developer. Thank you for packaging bubblejail.

However, I noticed that a few dependencies are incorrect.

1. Missing runtime dependency on bubblewrap
2. `desktop-file-utils` should be runtime dependency not make dependency
3. `python-jinja2` is not required at runtime only at build time
4. `libseccomp-devel` is not needed because bubblejail uses ctypes to integrate libseccomp
5. `notify-send` from `libnotify` is a recommended runtime dependency to send desktop notifications if bubblejail crashes during initialization

**Comment by nekopsykose** [comment]
thanks :)
