### ISSUE TITLE
Packaging Rust's development tools (rustup, rustfmt, clippy et al)

### ISSUE THREAD

**Issue by CuriouslyCurious** [chimera-linux/cports#203]
Getting a proper Rust dev environment up is at the moment quite tricky due to the Chimera-specific patches to Rust. I've read through them but haven't quite grasped exactly what they accomplish, so I need some clarifications. :P

I've been messing around with trying to package various Rust devtools that are currently not yet available, but have run into a bit of a wall due to either requiring a nightly version of the compiler or having Chimera-specific patches applied to downloaded binaries. `rustup` compiles but binaries downloaded does not link properly with libunwind (this might be me being bad/confused tho).

Tools that'd be nice to have:
* `rustfmt` (needs nightly) - format Rust code
* `rust-analyzer` (needs `rustfmt`) - Rust's LSP
* `rustup` (requires Rust patches?) - toolchain manager
* `clippy` (needs nightly) - linter
* `miri` (requires some libffi shenaniganry) - undefined behaviour finder

All these tools are in [Rust's main repo](https://github.com/rust-lang/rust/tree/master/src/tools) for the record.

There are some hacky ways I can get `rust-analyzer` packaged by compiling (or downloading) a nightly version and then using that to compile `rustfmt` so I can then compile `rust-analyzer`, but I don't feel like that is an ideal way of doing it.

What would be quite convenient would be to have `rustup` packaged like in [void](https://github.com/void-linux/void-packages/tree/master/srcpkgs/rustup) or [Alpine](https://git.alpinelinux.org/aports/tree/community/rustup?h=master) then it could be left up to users to download them via that. It'd also allow chimera users to dev on unstable branches of Rust instead of just the one's packaged here in cports.

Do you think these things could packaged in some way that isn't complete jank?

**Comment by q66** [comment]
third party toolchain binaries not working properly is not chimera's problem, therefore also not something i can or am going to do anything about

that also means rustup is not going to be available

best that could be done is build rustfmt and maybe clippy from the same tarball as the compiler during the compiler build and have packages of that, but that's as much as is going to happen

i think you're nagging the wrong place

**Comment by q66** [comment]
there was never any promise of compatibility with other musl-based systems, quite the contrary in fact - compiler-rt+libunwind being the system runtime library means binaries using libgcc(_s) as their runtime library are not directly compatible

in general toolchains have ways to address this and do not identify a target platform purely by a target triple (`arch-vendor-os`, e.g. `aarch64-unknown-linux-musl`), as the target triple is not an anambiguous way to fully identify a target

the rust toolchain has no such thing, as apparently rust developers seem to think they know better, and uses only a target triple to identify a platform; based on parts of this triple, it specifies things such as linkage parameters and others - that means even if the binaries from rustup directly worked, they will emit stuff that assumes other systems, as they have no way to identify what kind of system to emit for, they can at best guess

additionally, the rust team seems to want to be the ones distributing the toolchain binaries; they can do that, of course, however, those binaries are third party to chimera, so it's up to the rust team to provide a working toolchain (and it's up to users wanting that to happen to nag them), not chimera - there is absolutely nothing i can do about this (so this is not the place to open issues about this at)

so that's why you can't have rustup

rustfmt wil be added with the next version, it was already planned, but it will be tied to the specific compiler version that is packaged

**Comment by yoctozepto** [comment]
Packaging rustup does not make sense also in that it is a self-hosting package (well, Rust development ecosystem) manager.

Anyway, nowadays it seems that by having at least the following installed in the world (maybe a smaller base would be fine as well, not bothering to check now though):

```
base-full
chimera-repo-contrib
clang
curl
libgcc-chimera
```

allows one to succesfully use rustup's official installation method and it delivers a toolchain that seems to work for as long as it does not need to use the C compiler...

**Comment by nekopsykose** [comment]
that only works if you also symlink libgcc_s.so to libgcc_s.so.1 since the default rustup -linux-musl target will have `-lgcc_s` when linking (or at least that was the case on 1.76 when i checked, maybe they changed it in the past 4 versions)

**Comment by yoctozepto** [comment]
> that only works if you also symlink libgcc_s.so to libgcc_s.so.1 since the default rustup -linux-musl target will have `-lgcc_s` when linking (or at least that was the case on 1.76 when i checked, maybe they changed it in the past 4 versions)

FWIW, I did not have to. It was happy without the symlink too. Anyhow, it could not use the C compiler for some reason (did not bother to debug further but the autoconf-like log simply stated the C compiler is not usable :D ).

**Comment by nekopsykose** [comment]
the first thing i tried failed with exactly that:  

```
$ RUSTFLAGS="-Ctarget-feature=-crt-static"  cargo build --release
   Compiling libc v0.2.155
   Compiling proc-macro2 v1.0.86
   Compiling unicode-ident v1.0.12
   Compiling pin-project-lite v0.2.14
   Compiling autocfg v1.3.0
   Compiling futures-core v0.3.30
   Compiling futures-sink v0.3.30
   Compiling bytes v1.6.1
   Compiling futures-io v0.3.30
   Compiling pin-utils v0.1.0
   Compiling memchr v2.7.4
   Compiling itoa v1.0.11
   Compiling futures-task v0.3.30
   Compiling fnv v1.0.7
   Compiling once_cell v1.19.0
   Compiling httparse v1.9.4
   Compiling cc v1.1.6
   Compiling cfg-if v1.0.0
   Compiling hashbrown v0.14.5
   Compiling equivalent v1.0.1
   Compiling atomic-waker v1.1.2
   Compiling futures-channel v0.3.30
   Compiling ppv-lite86 v0.2.17
   Compiling anyhow v1.0.86
   Compiling httpdate v1.0.3
   Compiling smallvec v1.13.2
   Compiling getopt v1.1.7
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/bin:/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/bin:/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/bin:/usr/lib/ccache/bin:/home/demon/.local/bin:/home/demon/bin:/home/demon/lbin:/home/demon/.local/share/cargo/bin:/home/demon/.local/share/go/bin:/home/demon/.local/share/flatpak/exports/bin:/home/demon/.local/share/zvm/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin" VSLANG="1033" "cc" "-m64" "/tmp/rustcdOjbRq/symbols.o" "/home/demon/src/why/target/release/build/proc-macro2-2aaa1787ff388895/build_script_build-2aaa1787ff388895.build_script_build.a7df40c1abca1acc-cgu.0.rcgu.o" "/home/demon/src/why/target/release/build/proc-macro2-2aaa1787ff388895/build_script_build-2aaa1787ff388895.build_script_build.a7df40c1abca1acc-cgu.1.rcgu.o" "/home/demon/src/why/target/release/build/proc-macro2-2aaa1787ff388895/build_script_build-2aaa1787ff388895.632tbb7vohgkiyb6ohlzkpsm2.rcgu.o" "-Wl,--as-needed" "-L" "/home/demon/src/why/target/release/deps" "-L" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib" "-Wl,-Bstatic" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd-9e3271737799979c.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libpanic_unwind-4c1c7ab118cc5f35.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libobject-31059d048fd8f114.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libmemchr-4dc3b7f53f3b402f.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libaddr2line-556b787942975b60.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libgimli-3e999cbd821f19d5.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_demangle-21822f0e6b7cdefb.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libstd_detect-09a07f71e37263e3.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libhashbrown-823a6eadc824d6ac.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_alloc-5077514a6e44d5f0.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libminiz_oxide-a9cd1f496dec3a1a.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libadler-4eab1af5faf407c1.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libunwind-c1f62009d3a71342.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcfg_if-275322ea4ac54ad7.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/liblibc-6b2db73c8e3b6556.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/liballoc-2b62658611d149ab.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/librustc_std_workspace_core-9f33ce63021d8f8a.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcore-e789b40e8b60ba8e.rlib" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib/libcompiler_builtins-325d535ae4004bc5.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/demon/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/rustlib/x86_64-unknown-linux-musl/lib" "-o" "/home/demon/src/why/target/release/build/proc-macro2-2aaa1787ff388895/build_script_build-2aaa1787ff388895" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,--strip-all" "-nodefaultlibs"
  = note: ld: error: unable to find library -lgcc_s
```

are you sure `cargo`/`rustc` in your case is the one from .rustup and not /usr/bin?

**Comment by yoctozepto** [comment]
> the first thing i tried failed with exactly that:
> 
> ```
>   = note: ld: error: unable to find library -lgcc_s
> ```

In your case it is trying to link for some final binary. I said the rustup's use of clang was b0rken anyhow so I did not get to this part in my example. What worked after installing libgcc (and did not before) was rustc (else it would fail to execute even to show its version).

> are you sure `cargo`/`rustc` in your case is the one from .rustup and not /usr/bin?

Yes. ;-)

**Comment by nekopsykose** [comment]
> I said the rustup's use of clang was b0rken anyhow so I did not get to this part in my example.

well.. it's not. all of that works fine :) rustup doesn't even "use clang".

the thing being linked is a `build_script_build` which every single project that has a build.rs builds, which is in every dep tree ever

> What worked after installing libgcc (and did not before) was rustc (else it would fail to execute even to show its version).

sure, that's expected

so,  

> allows one to succesfully use rustup's official installation method and it delivers a toolchain that seems to work for as long as it does not need to use the C compiler...

is just incorrect, since it runs into the exact same issue it always has, and absolutely nothing has changed :p

**Comment by yoctozepto** [comment]
> > I said the rustup's use of clang was b0rken anyhow so I did not get to this part in my example.
> 
> well.. it's not. all of that works fine :) rustup doesn't even "use clang".

I meant "rustup's **rustc's** use of clang". My mind decided to skip the right part when writing this down...

> the thing being linked is a `build_script_build` which every single project that has a build.rs builds, which is in every dep tree ever

Not true. You can have deptrees without build.rs or with build.rs that does something other than trying to link C stuff - and these simply work (that was my point and it holds true). Though I agree that the unfortunate state is that many many packages do bring C into play and then it's bye-bye with rustup's rustc on Chimera Linux.

> > What worked after installing libgcc (and did not before) was rustc (else it would fail to execute even to show its version).
> 
> sure, that's expected

Just to clarify (and for posterity) what is happening without libgcc-chimera:

```
$ rustc
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /home/radek/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/librustc_driver-872b4b1a50a7b164.so)
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /home/radek/.rustup/toolchains/stable-x86_64-unknown-linux-musl/lib/libstd-9e3271737799979c.so)
$ cargo
Error loading shared library libgcc_s.so.1: No such file or directory (needed by /home/radek/.rustup/toolchains/stable-x86_64-unknown-linux-musl/bin/cargo)
```

> > allows one to succesfully use rustup's official installation method and it delivers a toolchain that seems to work for as long as it does not need to use the C compiler...
> 
> is just incorrect, since it runs into the exact same issue it always has, and absolutely nothing has changed :p

It is correct. No need to meddle with C = "working" rustup's rustc.

**Comment by nekopsykose** [comment]
> Not true. You can have deptrees without build.rs or with build.rs that does something other than trying to link C stuff - and these simply work (that was my point and it holds true).  
> It is correct. No need to meddle with C = "working" rustup's rustc.  

it does not, proc-macro2 has a build.rs, and it fails to build for the listed reason above, like in the log. every project that uses build.rs anywhere in the dep tree (which can do anything and isn't necessarily for "linking C deps") or uses proc-macro2 (anything that uses macros) fails.  

so this is the same as it was for years, where things fail with -lgcc_s- nothing has changed. i tested it back then too! it is the \*exact\* same list of stuff that works ootb and doesn't.

**Comment by nekopsykose** [comment]
if you want more proof rather than me just saying you're wrong, here you go  

```console
$ cargo init asd
$ cd asd
$ cat > build.rs <<-EOF
fn main() {
    println!("asd");
}
EOF
$ RUSTFLAGS="-Ctarget-feature=-crt-static" cargo build # it fails
```

**Comment by yoctozepto** [comment]
> if you want more proof rather than me just saying you're wrong, here you go
> 
> ```
> $ cargo init asd
> $ cd asd
> $ cat > build.rs <<-EOF
> fn main() {
>     println!("asd");
> }
> EOF
> $ RUSTFLAGS="-Ctarget-feature=-crt-static" cargo build # it fails
> ```

I don't do `-Ctarget-feature=-crt-static` and it works. ;-) The executables it produces run fine. Again, as I said - if I touch nothing C-related (feels like I said it a million times already), rustup's toolchain works "fine". I don't get where I say something untrue.

**Comment by nekopsykose** [comment]
> if I touch nothing C-related

the example has nothing C related in it, it's hello world in rust

> I don't do -Ctarget-feature=-crt-static and it works

yeah, it does, while defaulting to static which is not what you want most of the time

we clearly have very different definitions of 'the toolchain works' so obviously this is not going to go anywhere, if 'i can compile some projects in one specific configuration' counts as 'works'

**Comment by yoctozepto** [comment]
> > if I touch nothing C-related
> 
> the example has nothing C related in it, it's hello world in rust

Your example touches C linkage setting.

> > I don't do -Ctarget-feature=-crt-static and it works
> 
> yeah, it does, while defaulting to static which is not what you want most of the time

"Most of the time" might differ from person to person. There are legit reasons to distribute static stuff.

> we clearly have very different definitions of 'the toolchain works' so obviously this is not going to go anywhere, if 'i can compile some projects in one specific configuration' counts as 'works'

I have claimed truthfully that it works in certain scenarios only. My only goal was to give an update on the current state of how far rustup can go and this is as far as it can go now.

**Comment by yoctozepto** [comment]
On the flip side, where we (I think) all agree here (and also with the creators of rustup) is that rustup is not meant to be a distribution tool for packaging the rust ecosystem.
