### ISSUE TITLE
add a way to prevent ci from failing on update check returning results

### ISSUE THREAD

**Issue by triallax** [chimera-linux/cports#2038]
right now the ci fails if running `update-check` on any modified or added template returns any new versions, which is usually nice but sometimes the template is intentionally not updated/an older version is packaged in the pr, it'd be nice to have a way to ignore that error in these cases, either per-pr or per-commit (maybe something like "[ci skip]"?)

**Comment by q66** [comment]
when intentionally packaging older version, usually the right thing is to add newer version to ignore though

**Comment by triallax** [comment]
fair that's usually the case, but still not necessarily true for the other cases i mentioned (e.g. just relbumping an outdated package that i don't want to bump in the same pr)
