### ISSUE TITLE
initramfs-tools man page does not render properly

### ISSUE THREAD

**Issue by wezm** [chimera-linux/cports#205]
Running `man initramfs-tools` shows the raw markup and not a formatted document. It renders ok with `mandoc -man /usr/share/man/man7/initramfs-tools.7` though so I'm not sure where the problem is occurring. I don't know man syntax really at all and nothing leaps out as wrong in the source file. However it does start with `W.TH`, which doesn't get syntax highlighted in my editor, whereas `.TH` does... changing this didn't fix it though.

**Comment by q66** [comment]
when you modify a manpage, you need to refresh the database to make it show that
