### ISSUE TITLE
mold: missing /usr/lib/LLVMgold.so

### ISSUE THREAD

**Issue by ptrcnull** [chimera-linux/cports#2154]
i'm not exactly sure why it happens, but:
```
mold: fatal: could not open plugin file: Error loading shared library /usr/bin/../lib/LLVMgold.so: No such file or directory
```

**Comment by q66** [comment]
this is provided by binutils-common, is mold using the bfd linker plugins for lto?

**Comment by nekopsykose** [comment]
no, clang does

```
  if (llvm::sys::path::filename(Linker) != "ld.lld" &&
      llvm::sys::path::stem(Linker) != "ld.lld" &&
      !ToolChain.getTriple().isOSOpenBSD()) {
    // Tell the linker to load the plugin. This has to come before
    // AddLinkerInputs as gold requires -plugin and AIX ld requires -bplugin to
    // come before any -plugin-opt/-bplugin_opt that -Wl might forward.
    const char *PluginPrefix = IsOSAIX ? "-bplugin:" : "";
    const char *PluginName = IsOSAIX ? "/libLTO" : "/LLVMgold";
```

clang/lib/Driver/ToolChains/CommonArgs.cpp

**Comment by nekopsykose** [comment]
i don't think libLTO is a linker plugin either (despite the pkgdesc), since they work by dlopen+dlsym(onload) and it does not export such a thing

**Comment by nekopsykose** [comment]
could probably create a package just for plugin-api.h and so llvm itself will build LLVMgold.so in llvm/tools/gold, and then we don't need the binutils one

**Comment by q66** [comment]
the plugin is not really useful for any linker that can't use it though, can mold?

**Comment by nekopsykose** [comment]
yes, it's required to do lto and ends up calling into liblto/llvm through it

**Comment by q66** [comment]
then what we should do is probably add binutils-common dep to mold

**Comment by nekopsykose** [comment]
sure
