### ISSUE TITLE
Missing Log Entries of Recoving EXT4 Errors

### ISSUE THREAD

**Issue by softlemonade** [chimera-linux/cports#2281]
Hello.

today, my chimera installation suddenly seemed to have lost power. After booting, these errors were displayed:
![12cd03ae_ET0nx_wwQ--snuURR1X1Kw](https://github.com/chimera-linux/cports/assets/171420399/db8c30e0-7f7e-4d6a-9134-7fb782162b77)

After rebooting, i saw some messages for a short time that it tried to recover. Which seemed to be successful since i can now use the laptop again like before. I tried to search for them in /var/log/* but couldn't find log messages from this recovery.

Or rather, i found this:
```
user@chimerachimera:/var/log$ doas grep -riE "2024-06-20.*EXT4"
./kern.log:2024-06-20 09:42:14 notice kernel: EXT4-fs (dm-3): error count since last fsck: 10
./kern.log:2024-06-20 09:42:14 notice kernel: EXT4-fs (dm-3): initial error at time 1718869019: ext4_orphan_get:1420
./kern.log:2024-06-20 09:42:14 notice kernel: EXT4-fs (dm-3): last error at time 1718869019: ext4_orphan_get:1420
```

But i think that is not what i saw in the console after the startup.

Not sure what the consequences of this are (is my SSD broken? is there a EXT4 bug?) - but my impression is that log messages are lost which makes it difficult to understand.

**Comment by q66** [comment]
the above log and shell is from the initramfs, before root filesystem is mounted at all
