### ISSUE TITLE
Can’t bootstrap cbuild

### ISSUE THREAD

**Issue by wjk** [chimera-linux/cports#2378]
Greetings! I want to write some cports code for a program that I am interested in using ([NEXTSPACE](https://github.com/trunkmaster/nextspace) and its dependencies). I forked this repo and created a signing key successfully. However, when I run `./cbuild binary-bootstrap`, it complains the `base-cbuild` package does not exist. This package very much exists, but when I try to install it via `apk add`, I get the following error:

```
ERROR: unable to select packages:
  base-cbuild-0.1-r6:
    breaks: chimera-repo-main-0.1-r0[!base-cbuild]
    satisfies: world[base-cbuild]
```

What does this mean, and what can I do to get it to work?

**Comment by q66** [comment]
you cannot install base-cbuild on your system (it's specifically made to be used for cbuild containers only)

binary-bootstrap should work just fine however, unless you have remote repos disabled or something

**Comment by wjk** [comment]
This is the error I get:

<img width="1222" alt="Screenshot 2024-06-30 at 5 19 57 PM" src="https://github.com/chimera-linux/cports/assets/1915951/4ad7029a-feb3-44e0-9979-34faf799c53e">

**Comment by q66** [comment]
on what host system? this looks like your keys in the cports tree may be messed up somehow? is the git tree clean?

**Comment by wjk** [comment]
My host is macOS; my VM program is [UTM](https://github.com/utmapp/UTM).

I ran `git clean -fdx` in the root of the repo, then run `./cbuild keygen` to regenerate keys. The same error still appears when I run `./cbuild binary-bootstrap`.

**Comment by q66** [comment]
post output of `find bldroot|sort`

**Comment by wjk** [comment]
```
bldroot
bldroot/altbinpkgs
bldroot/binpkgs
bldroot/boot
bldroot/builddir
bldroot/cbuild_cache
bldroot/destdir
bldroot/dev
bldroot/etc
bldroot/etc/apk
bldroot/etc/apk/keys
bldroot/etc/apk/keys/wjk-6681cdae.rsa.pub
bldroot/etc/apk/world
bldroot/host
bldroot/lib
bldroot/proc
bldroot/sources
bldroot/stagepkgs
bldroot/sys
bldroot/tmp
bldroot/usr
bldroot/usr/lib
bldroot/usr/lib/apk
bldroot/usr/lib/apk/db
bldroot/usr/lib/apk/db/installed
bldroot/usr/lib/apk/db/lock
bldroot/var
bldroot/var/cache
bldroot/var/cache/apk
bldroot/var/cache/misc
bldroot/var/log
bldroot/var/log/apk.log
```

**Comment by q66** [comment]
that looks wrong, the key is not copied; the static repo key is in `etc/apk/keys` and the `setup_keys` function in `src/cbuild/core/chroot.py` is supposed to copy that as well as your own keys

**Comment by q66** [comment]
```
q66@chimera: /home/q66/cports$ ls etc/apk/keys 
total 8
-rw-r--r--  1 q66 q66 451 Jun  2 13:18 q66@chimera-linux.org-61a1913b.rsa.pub
```

```
q66@chimera: /home/q66/cports$ ls -l bldroot/etc/apk/keys 
total 24
-rw-r--r--  1 q66 q66 451 Jun  2 13:18 garga@FreeBSD.org-65ea07c9.rsa.pub
-rw-r--r--  1 q66 q66 451 Jun  2 13:18 q66@chimera-linux.org-61a1913b.rsa.pub
-rw-r--r--  1 q66 q66 451 Jun  2 13:18 q66@chimera-linux.org-6473714c.rsa.pub
```

**Comment by q66** [comment]
do `rm -rf bldroot` and try again, maybe something got messed up the first time and now it's stuck

**Comment by wjk** [comment]
Didn’t help. I do notice that `etc/apk/keys` is empty, while `bldroot/etc/apk/keys` contains one key, which was the one I generated earlier using `./cbuild keygen`.

**Comment by q66** [comment]
if your etc/apk/keys is empty, that means your repo clone is in a bad state, because it's not actually empty: https://github.com/chimera-linux/cports/tree/master/etc/apk/keys

**Comment by wjk** [comment]
I completely deleted my clone of cports and redownloaded it. Works great now. Thanks!
