### ISSUE TITLE
Chimera does not boot after `apk upgrade`

### ISSUE THREAD

**Issue by sidkshatriya** [chimera-linux/cports#2380]
Chimera `apk upgrades` have generally been very reliable. The system is always bootable after the upgrade. However, this time there is an issue. I've been able to repeat this twice.

So the upgrade looks like this:
```
$ doas apk update && doas apk upgrade
...
Executing sd-tools-0.99.0-r2.trigger
Executing base-shells-0.1-r0.trigger
Regenerating /etc/shells...
Executing shadow-4.16.0-r1.trigger
Executing udev-256.1-r0.trigger
Error relocating /usr/bin/udevadm: renameat2: symbol not found
Updating udev hwdb...
Error relocating /usr/bin/udev-hwdb: renameat2: symbol not found
Executing dinit-chimera-0.99.7-r1.trigger
...
```

I'm not sure if the "symbol not found" messages are harmless or not. 

Now when I try to reboot the system, it gets stuck at:
```
...
[    0.513306] Run /init as init process
[    0.513485]   with arguments:
[    0.513632]     /init
[    0.513743]     splash
[    0.513859]   with environment:
[    0.514011]     HOME=/
[    0.514127]     TERM=linux
[    0.514259]     BOOT_IMAGE=/vmlinux-6.9.7-0-generic
Loading, please wait...
+ [ -z '' ]
+ BOOT=local
+ [ -n '' ]
+ [ '' '=' none ]
+ resume=''
+ mount -t tmpfs -o 'nodev,noexec,nosuid,size=10%,mode=0755' tmpfs /run
+ mkdir -m 0700 /run/initramfs
+ [ -n /run/initramfs/initramfs.debug ]
+ exec
sh: can't access tty; job control turned off
(initramfs) 
```

**Comment by subnut** [comment]
Probably related to https://github.com/chimera-linux/cports/commit/98a6ea5022843171cff564f48fd5f9f7489cbda3

That commit reverts `udev` back to `254`, but your system seems to be installing `256.1`

Probably because apk is thinking `256.1-r0` > `254-r11`, but I might be totally wrong.

@nekopsykose

**Comment by q66** [comment]
It seems the downgrade never got propagated into the repos as the openssl test suite got stuck

**Comment by q66** [comment]
also the `renameat2` messages look interesting, i haven't seen those... could be related to whatever issue people are facing

**Comment by q66** [comment]
the issue with the renameat2 is that something is holding back your musl upgrade (perhaps a stuck musl-dbg package from a local repo or something?)

e84e3b9fa0ac7896f8897c1d758467c2b9ab4054 should take care of the downgrade propagating so `upgrade --available` should be ok now

**Comment by sidkshatriya** [comment]
Thanks for the info -- indeed this was a musl issue -- I had a custom musl installed which was not being upgraded. Moving to the musl in the chimera repo fixed the problem.
