### ISSUE TITLE
[Feature Request] BOLTing Linux

### ISSUE THREAD

**Issue by Drsheppard01** [chimera-linux/cports#2417]
Can you add optimizations for Linux kernel follow this guide

https://github.com/llvm/llvm-project/blob/main/bolt/docs/OptimizingLinux.md

**Comment by q66** [comment]
no

read the article you linked, it requires profiling actual workloads on a target system

**Comment by Drsheppard01** [comment]
Thx for answer, it can't be possible implement this optimizations in server instead client system?
