### ISSUE TITLE
cfi .a's can't be used

### ISSUE THREAD

**Issue by nekopsykose** [chimera-linux/cports#2522]
currently if you try link against a cfi-built .a you merely get

```
ld: error: inconsistent LTO Unit splitting (recompile with -fsplit-lto-unit)
```

this is because fsanitize=cfi implies -fsplit-lto-unit, and -fsplit-lto-unit requires everything built with lto to also have it set.

it works to merely add

```diff
--- a/src/cbuild/core/profile.py
+++ b/src/cbuild/core/profile.py
@@ -113,6 +113,7 @@ def _get_archflags(prof, tmpl, hard):
         sflags.append("-fno-sanitize-recover")
 
     if lto:
+        sflags.append("-fsplit-lto-unit")
         if tmpl.options["ltofull"]:
             sflags.append("-flto")
         else:
```

but that requires a world rebuild

**Comment by BergmannAtmet** [comment]
Is a world build happening anytime soon?

I basically use Chimera in CI to test against latest LLVM to detect any potential issues early. And use Alpine for static builds. I wanted to do the latter in the same Chimera run, but came across this issue and didn't check back if it was ever fixed.
