### ISSUE TITLE
missing depsorter support

### ISSUE THREAD

**Issue by nekopsykose** [chimera-linux/cports#2534]
fstring : `kde1-kdeutils-1.1.2-r0: ERROR: dependency list 'depends' contains an invalid value (must be a string or a list expansion)`

(`depends = [f"kde1-kdebase~{pkgver}"]`)

fstring, call: `gcc-14.1.1_git20240720-r0: ERROR: dependency list 'hostmakedepends' contains an invalid value (must be a string or a list expansion)`

(`f"binutils-{self.profile().arch}",`)

* maybe, didn't check [self.with_pkgver]

**Comment by q66** [comment]
fun, i thought i had explicitly tested this
