### ISSUE TITLE
Missing character set support in the default installation

### ISSUE THREAD

**Issue by catgirlconspiracy** [chimera-linux/cports#2633]
(Is this where I report issues like this? I'm gonna assume this is where I report issues like this.)

The default desktop installation (`gnome` metapackage, I don't know about other desktop envs) is missing fonts for a lot of non-European scripts, as well as emoji. Looking at https://wikipedia.org shows a lot of missing characters. Also, the GNOME console doesn't show emoji. I installed these packages which seems to at least cover everything I could find:

* `fonts-noto`
* `fonts-noto-emoji-ttf`
* `fonts-noto-sans-cjk`

IMO these should be in the default installation.

**Comment by nekopsykose** [comment]
> (Is this where I report issues like this? I'm gonna assume this is where I report issues like this.)

yeah, it is

> I installed these packages which seems to at least cover everything I could find:

yeah, noto+noto-cjk+noto-emoji is basically every scripture

> IMO these should be in the default installation.   

agree, not sure where to put it. probably a default-auto-installed thing somewhere...

**Comment by nekopsykose** [comment]
currently 'gnome' meta hard-depends on 

```
    "fonts-cantarell-otf",
    "fonts-source-code-pro-otf",
```

since these are default (that's ok). then base-full-fonts has just 'dejavu' (so people get that by default)

probably would just make base-full-fonts pull those i guess after moving them

the main issue is that while noto+emoji is 26mb+10mb, sans/serif cjk is 159/238mb, which is proobably a bit much to just autoinstall, but not sure how i feel about it. at least the first two is more uncontroversial

**Comment by nekopsykose** [comment]
added the first two; i'll leave this open as a reminder for cjk i guess since not sure there, but this is basically good enuf for now

**Comment by nekopsykose** [comment]
what does liberation have in it that dejavu (already pulled) doesn't

but yea prolly it's 12kb lol

**Comment by nekopsykose** [comment]
nvm is 5mb

**Comment by nekopsykose** [comment]
thanks :)  

i guess the cros fonts are an alternative to liberation but they're missing a row in that table and we don't have them yet
