### ISSUE TITLE
cbuild can't build on systems with SELinux

### ISSUE THREAD

**Issue by catgirlconspiracy** [chimera-linux/cports#2675]
I can't use cbuild on a system with SELinux enabled (Fedora 40), neither natively nor from Chimera running in a container:
```
...
=> apk-tools-devel-3.0.0_pre6-r1: running pre_pkg hook: 032_check_xattrs...
=> apk-tools-devel-3.0.0_pre6-r1: undeclared xattrs found for:
  /home/mara/Code/cports/bldroot/destdir/apk-tools-devel-3.0.0_pre6/usr
  /home/mara/Code/cports/bldroot/destdir/apk-tools-devel-3.0.0_pre6/usr/lib
  /home/mara/Code/cports/bldroot/destdir/apk-tools-devel-3.0.0_pre6/usr/include
  /home/mara/Code/cports/bldroot/destdir/apk-tools-devel-3.0.0_pre6/usr/lib/libapk.so
  [...more files]
=> apk-tools-devel-3.0.0_pre6-r1: ERROR: cannot proceed
```

It gets hung up on the SELinux label xattr:
```
$ python3 -c "import os; print(os.listxattr('bldroot/destdir/apk-tools-devel-3.0.0_pre6/usr/lib/libapk.so', follow_symlinks=False))"
['security.selinux']
```

Ignoring that attribute in 032_check_xattrs works, but maybe there's a better approach.

**Comment by sidkshatriya** [comment]
I don't believe cbuild is intended to ever work on fedora without a container.

I don't know much about SELinux but if it does not work you should probably be adding changing configuration for SELinux on Fedora. chimera is simply running under the policy of the host fedora.

**Comment by q66** [comment]
i don't know if there is anything that can be done from our side about selinux hijacking xattrs on everything, maybe you can exclude it somehow? is the `security.selinux` namespace something that is physically stored in the file or is it just transient?

**Comment by q66** [comment]
if it's a physical xattr, then skipping it is a wrong thing to do because it means selinux actually affects the build output which is Bad

if it's just "there" ephemerally, then having the checker skip it is fine

which is why i need to know (i generally avoid redhat-based systems so i don't have any)

**Comment by q66** [comment]
but then maybe we can just always skip it anyway because cbuild will generally nuke all xattrs and re-create them based on template in a fakerooted environment... i'd need an RH environment to verify whether that's really the case though

**Comment by q66** [comment]
looks like no xattrs are recorded, so it should be fine
