### ISSUE TITLE
helper to convert from host to chroot path

### ISSUE THREAD

**Issue by nekopsykose** [chimera-linux/cports#2730]
mostly would instantly be used for https://github.com/chimera-linux/cports/issues/2683

example impl in https://github.com/chimera-linux/cports/pull/2576 host_path_to_chroot

**Comment by nekopsykose** [comment]
locally i also used something like this for something like

```
self.do("llvm-profdata", "merge", (self.cwd / "someshit").glob("*.profdata"), "-output", "merged.profdata")
```

where by default this fails, because the self.cwd view is host, but .do executes in chroot context. so sometimes it's needed to convert these to be able to pass cwd-based globs into something to a .do (since .glob is afaict only usable from a pathlib.Path, but the only way to get one of those is self.cwd or similar, since we can't import Path and do Path(".").glob() for relative, and the existing chroot_ vars don't work because the glob is done from host context)

unrelatedly that means another useful thing to add is something that is just Path(".") instead of /full/path for cwd, but i have no idea what that would be called

**Comment by q66** [comment]
the issue is mainly that the host view may differ based on where the chroot path is, as the chroot consists of multiple mounts which may point to wildly different paths outside, so implementing this generically is bound to be inefficient, as it would require multiple path checks to see what to map to

normally when using stuff right now you you do something like... `self.chroot_builddir / path.relative_to(self.builddir)` or equivalent for different mounts (basically using the "closest" defined path pair to what you are dealing with)

this is not particularly efficient either and is somewhat clunky but so far i haven't been able to find anything better

**Comment by nekopsykose** [comment]
guess so

the second case of having a pathlib.Path(".") exposed would solve my own immediate issue and should be very easy :)

**Comment by q66** [comment]
how would it be easy? having an actual relative path object is never useful since we never change the physical cwd, so it would not match anything ever

**Comment by nekopsykose** [comment]
does cbuild rely on its own cwd being in cports presently for any internals or nah

if not you could make cwd `.` and make it chdir somewhere more useful for every step

**Comment by nekopsykose** [comment]
> the issue is mainly that the host view may differ based on where the chroot path is, as the chroot consists of multiple mounts

i only see this ever being useful relative to builddir and not any of the others so that seems fine

**Comment by nekopsykose** [comment]
> if not you could make cwd . and make it chdir somewhere more useful for every step

(this is a terrible idea)

**Comment by nekopsykose** [comment]
i think the relative_to is fine actually, and you don't need the first part either; just `path.relative_to(self.builddir)` alone gives you a relative path that should work fine when passed to .do, but self.builddir is not something that exists since we removed it :P

**Comment by nekopsykose** [comment]
seems self.srcdir is the exact same path though so that works

**Comment by q66** [comment]
> > the issue is mainly that the host view may differ based on where the chroot path is, as the chroot consists of multiple mounts
> 
> i only see this ever being useful relative to builddir and not any of the others so that seems fine

is used with destdir too
