### ISSUE TITLE
cbuild creates bldroot/builddir/package-version for -t

### ISSUE THREAD

**Issue by nekopsykose** [chimera-linux/cports#2746]
when having something like

```
[build]
build_root = /tmp/bldroot
```

and doing `./cbuild pkg -t main/xyz`, `/tmp/bldroot/builddir/xyz-version` is created as well as `/tmp/bldroot.randomchars/......`

should prolly not make the former unless this is complicated to handle or something

**Comment by q66** [comment]
i can't repro this at all (i set `build_root`, then ran `binary-bootstrap`, then tried building stuff with `-t` and i don't see anything in `/tmp/bldroot/builddir`)

**Comment by nekopsykose** [comment]
i think i'm stupid cause i can't repro it anymore either
