### ISSUE TITLE
duplicate base-python dep with some virtual spec in depends

### ISSUE THREAD

**Issue by nekopsykose** [chimera-linux/cports#2838]
```
$ apk info -R python-lit
python-lit-18.1.8-r0 depends on:
base-python3.12~3.12
base-python3.12~3.12
cmd:FileCheck
cmd:not
```

when building it with

```
depends = [
    "cmd:FileCheck!llvm",
    "cmd:not!llvm",
]
```

doing `!llvm-tools` (like in the template currently) has it only once, but doing `!llvm` places it twice

just something i noticed while building it initially

**Comment by q66** [comment]
the odd thing is that before the fix the package generation cmdline is identical (in both cases it contains two dependencies) but the adbdump ends up different

so i have no idea what's going on there
