### ISSUE TITLE
npm package support in cbuild

### ISSUE THREAD

**Issue by tulilirockz** [chimera-linux/cports#2916]
I was trying to package [decibels](https://gitlab.gnome.org/GNOME/Incubator/decibels) and it seems to depend on the typescript compiler, and the typescript compiler is only really packaged for npm. Would it be interesting to integrate npm package support into cbuild or is that out of scope/not wanted? I would love to try to help out with that

**Comment by nekopsykose** [comment]
not sure what support would be required, packaging npm things like typescript amounts to 'you download the tarball and just copy the contents to /usr/share/node_modules' or equivalent, with nothing interesting happening there. see for instance testing/typescript in alpine

actually packaging npm deptrees is not possible and there's nothing else that would be useful in this case..

**Comment by tulilirockz** [comment]
> not sure what support would be required, packaging npm things like typescript amounts to 'you download the tarball and just copy the contents to /usr/share/node_modules' or equivalent, with nothing interesting happening there. see for instance testing/typescript in alpine

then in that case should I use something like `build_style = "meta"` for that? makes sense honestly, adding a build style for that probably wouldnt really ammount to anything then

**Comment by tulilirockz** [comment]
oh my god you can just not use a build style i didnt know that

**Comment by nekopsykose** [comment]
yeah, the only thing i don't like is people might actually use that as a sign for 'add random nodejs cli tool as a package' and as a whole that ordeal is scary :|  

but with a quick requirement of 'that tool has to be used in an actual build' tsc is ok :)

**Comment by nekopsykose** [comment]
so basically

```
def install(self):
    self.install_license("package/LICENSE.txt")
    self.install_files("package", "usr/share/node_modules", name="typescript")
    self.uninstall("usr/share/node_modules/typescript/LICENSE.txt")
    self.install_link() # tsc+tsserver rel links to bin/ above ^
```

p much

**Comment by tulilirockz** [comment]
> yeah, the only thing i don't like is people might actually use that as a sign for 'add random nodejs cli tool as a package' and as a whole that ordeal is scary :|

makes complete sense honestly, eventually someone will think "ehrm ill package leftpad for chimera linux 🤓 " cuz of that

**Comment by tulilirockz** [comment]
thx for the help! - didnt know this stuff
