### ISSUE TITLE
base-minimal depends on base-full?

### ISSUE THREAD

**Issue by wezm** [chimera-linux/cports#3150]
Is this intentional?

```
$ apk info --depends base-minimal
base-minimal-0.5-r1 depends on:
base-full=0.5-r1
```

https://github.com/chimera-linux/cports/blob/6256f88ac394807bc2dbba1cbcf43364ed7ad435/main/base-full/template.py#L217-L220

Just tried installing a minimal system in a VM and was surprised to see `base-full` installing when I specififed `chimera-bootstrap /media/root base-minimal mkfs`.

**Comment by sidkshatriya** [comment]
To understand, why is this the case ?

**Comment by nekopsykose** [comment]
base-full doesn't depend on anything itself. only its subpackages do:

```
    self.install_if = [self.parent, "!base-minimal"]
    self.depends = [
        "dhcpcd",
        "iwd",
        "openssh",
    ]
```

base-minimal depends on base-full, but if you have it it prevents every subpackage of base-full from installing, so it excludes every other subpackage.
