### ISSUE TITLE
Cross-compiled Go binaries don't seem to work

### ISSUE THREAD

**Issue by wezm** [chimera-linux/cports#3171]
Perhaps this is a known aspect of the go build style but I tried cross-compiling a couple of packages using that style and they don't work on the target machine.

I'm building x86_64 packages on an aarch64 host. The issues include a reference to `/lib64` in the binary. E.g. `fzf` cross-compiled with `./cbuild -a x86_64 main/fzf`:

```
# ldd /bin/fzf
        /lib64/ld-linux-x86-64.so.2 (0x77c44b21b000)
```

whereas a non-cross built binary:

```
# ldd /bin/fzf
        /lib/ld-musl-x86_64.so.1 (0x764abdf5d000)
        libc.so => /lib/ld-musl-x86_64.so.1 (0x764abdf5d000)
```

Running one of these cross-built binaries yields:

```
# fzf
/bin/sh: fzf: not found
```

**Comment by nekopsykose** [comment]
that should hopefully fix it. i'm not sure why they even come out dynamically linked (if they were static they would work, since no ldso would be chosen), but this should make the dynamic case work too

**Comment by nekopsykose** [comment]
probably a =pie quirk for the dyn part i guess, but doesn't matter anyway :)

**Comment by wezm** [comment]
Thanks @nekopsykose that fixed it.
