### ISSUE TITLE
vulkan-tools broken due to hardening

### ISSUE THREAD

**Issue by JamiKettunen** [chimera-linux/cports#319]
As reported in https://github.com/chimera-linux/cports/commit/280164a5401c807850bcc5bdd9065a65f1544ba3#commitcomment-124623890:
![image](https://github.com/chimera-linux/cports/assets/47358222/7c28a42f-595f-49f4-b5d9-b2c377564fdc)

**Comment by khanhncm** [comment]
Thank you, man. I don't know if it's worth  it to make an issue .
