### ISSUE TITLE
incus: Adding an environment file in /etc/default

### ISSUE THREAD

**Issue by cmspam** [chimera-linux/cports#3206]
Currently, some options or add-ons to Incus, such as a UI, require setting environment variables for incusd.

Would it be acceptable to introduce a file, /etc/default/incus, where users can define such environment variables? This approach is adopted in other distributions, such as Zabbly's ubuntu/debian builds and openSUSE's upcoming packages  of Incus.

With this in place, we could modify the incus service definition in /usr/lib/dinit.d/incus to include:

```
env-file = /etc/default/incus
```

While users can manually copy /usr/lib/dinit.d/incus to /etc/dinit.d/incus and modify it, this additional step may be unnecessary if we provide a standardized configuration file. Given that many users might need to customize settings for a UI, alternative EDK2/OVMF builds, or other use cases, having a default environment file would simplify the process.

Would this change be acceptable? 

As a newcomer, if I’ve misunderstood how Chimera Linux works or if there’s already a better way to achieve this, please forgive my oversight and kindly let me know.

**Comment by nekopsykose** [comment]
sure, look at main/tailscale for how that looks

**Comment by cmspam** [comment]
I don't mind doing it at all.

**Comment by cmspam** [comment]
This was a bigger PR than last time. If changes and squashing are needed, I'm ready this time 🤣
