### ISSUE TITLE
Fingerprint on GNOME settings broken on a Thinkpad T440p

### ISSUE THREAD

**Issue by Eggmanplant** [chimera-linux/cports#3330]
I recently got a Thinkpad T440p. First thing I did was install Linux (Chimera Linux in my place). Next I updated the BIOS to version 2.56.

The "Scan new fingerprint" button in fingerprint settings in gnome settings simply does nothing. After opening the fingerprint 
settings the fingerprint sensor flashes for a few seconds.

I did a local install with systemd-boot and merged boot and efi using the gnome image, and enabled NetworkManager and GDM.

If I run the settings app (gnome-control-center) with the verbose flag and press the add fingerprint button, it outputs:
`20:14:23.0384                  Gtk[ 7915]:CRITICAL: gtk_widget_is_ancestor: assertion 'GTK_IS_WIDGET (widget)' failed`

The scanner gets detected as Validity VFS5011.

Please help!

P.S. It did the same before the BIOS update.

**Comment by JamiKettunen** [comment]
works for a new finger (without deleting existing ones) on my Minisforum V3 tablet but originally I added mine via `fprintd-enroll` from terminal. also seems like an upstream issue: https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/3208

**Comment by Eggmanplant** [comment]
Yes, I discovered yesterday. Sorry for not updating the post.

**Comment by Eggmanplant** [comment]
But, thanks for the issue link!
