### ISSUE TITLE
Secure mimalloc mode

### ISSUE THREAD

**Issue by redactedontop** [chimera-linux/cports#3352]
Hello.

I'm wondering if this uses mimalloc built in secure mode by default? It could be a good substitute for mallocng (as it's faster and just as secure), and then non-secure and mallocng versions.

Thanks,
Alex <3

**Comment by q66** [comment]
https://github.com/chimera-linux/cports/blob/master/main/musl/files/mimalloc.c

**Comment by redactedontop** [comment]
How could I build it as secure by default?

**Comment by redactedontop** [comment]
I still wanna use mimalloc...
