### ISSUE TITLE
How to use secure mimalloc instead of mallocng

### ISSUE THREAD

**Issue by redactedontop** [chimera-linux/cports#3353]
Hello again.

I believe secure mimalloc, even though slower than non-secure mimalloc, is still faster than mallocng.
How could I use it with musl?

Thanks,
Alex.
PS: if mallocng is faster than secure mimalloc, please notify me.

**Comment by q66** [comment]
having your other issue closed is not an invitation for opening a new one, and i already showed you how it's configured
