### ISSUE TITLE
Minecraft won't run

### ISSUE THREAD

**Issue by PurpleVsGreen** [chimera-linux/cports#3369]
Hello, I followed the official documentation on how to get Minecraft running.
In the error it says it can't load `libopenal` because it can't load `libstdc++.so.6`. The env trick is specified as a wrapper exactly like in the documentation.

Any idea?

**Comment by PurpleVsGreen** [comment]
Settings were b0rked, my bad.

**Comment by sewnie** [comment]
Come on man..
