### ISSUE TITLE
run_check is True on crossbuild

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#34]
Using `run_check` this way in a template:
```
if current.run_check:
   makedepends += ["zlib-devel"]
```
makes `zlib-devel` package getting installed even on crossbuilding.
Is it the right way to use it ? If such, `run_check` should be set to false on crossbuild.

**Comment by yopito** [comment]
with `check` enabled (in `etc/config.ini` for instance)

**Comment by q66** [comment]
it shouldn't be true, but also conditionally installing dependencies only when checks are enabled is an antipattern - don't do that

i'm probably going to discard any kind of concept of "checkdepends" as well, packages should be built with an identical environment regardless of if testing or not
