### ISSUE TITLE
remove DONTSTRIP from cbuild/wrappers/install wrapper

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#37]
`cbuild/wrappers/install.sh` sets environment variable `DONTSTRIP`, that makes `install(1)` informs about it each item it's called with the following: "`install: DONTSTRIP set - will not strip installed binaries`"

Apart from generating a lot of log, this sentence regulary makes various packages provided testsuites fail just because of its presence.

Since `STRIPBIN` is already set in this wrapper, `DONTSTRIP` is not really required. So we can safely remove `DONTSTRIP` from `cbuild/wrappers/install.sh`.

**Comment by q66** [comment]
arguably these should be fixed, since the message shouldn't harm anything at all, but fair enough

**Comment by yopito** [comment]
I agree, but sometimes it's really painful to figure out. Like gnu autoconf and it's 527 tests, with 3 fails just because of this ...
