### ISSUE TITLE
spdx parser should handle LicenseRef- fragments

### ISSUE THREAD

**Issue by nekopsykose** [chimera-linux/cports#373]
e.g. `SPDX-License-Identifier: GPL-2.0-or-later WITH LicenseRef-isync-GPL-exception`  

`custom:` works but might as well just handle the LicenseRef token

**Comment by q66** [comment]
the reason i never implemented this is that i am not really sure how - particularly, according to the specification, the above is not a valid spdx license expression (licenseref never applies to exceptions according to the v2 spec - v3 spec adds more stuff for it but still does not permit LicenseRef for exceptions, see https://github.com/spdx/spdx-spec/issues/153)

so i'm not really sure what to do...

the current v3 spec syntax is https://spdx.github.io/spdx-spec/v3.0/annexes/SPDX-license-expressions/, maybe i could implement that but it would not help us with the above

**Comment by nekopsykose** [comment]
>  the above is not a valid spdx license expression  

yea, that example is not

but separate from that example e.g. kde uses a regular `LicenseRef-KDE-Accepted-GPL` or whatever, and those are valid
