### ISSUE TITLE
Linux kernel cross builds fail early

### ISSUE THREAD

**Issue by misanthrop** [chimera-linux/cports#379]
```
./cbuild -a aarch64 pkg main/linux-rpi
=> cbuild: clearing sysroot for aarch64...
=> setting up sysroot for aarch64...
=> cbuild: installing virtual provider for aarch64...
=> linux-rpi-6.1.41-r0: ERROR: cannot be built, it's currently broken: linux-devel does not come out right
```

It seems like intended, but why? Is there a way to workaround that?

**Comment by q66** [comment]
not as far as i can tell (unless commenting out the `broken =` counts)

it isn't possible to crosscompile kernel in a way where the development headers come out correct as in usable for native compilation of out of tree modules, so it's disabled
