### ISSUE TITLE
Missing wayland-protocols-devel?

### ISSUE THREAD

**Issue by AlbertoGP** [chimera-linux/cports#517]
Hi, I’m trying to compile a program using wayland, I get the following error message:

```
In file included from rglfw.c:95:
./external/glfw/src/wl_init.c:43:10: fatal error: 'wayland-xdg-shell-client-protocol.h' file not found
#include "wayland-xdg-shell-client-protocol.h"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I’ve installed `wayland-devel`, `wayland-devel-static`, and `wayland-protocols`, but I do not see any other package that seems relevant.
Searching for that `.h` file name in the package list (“Contents”) also did not yield any result.

Is there a missing `wayland-protocols-devel` package, or should I get that file from somewhere else?

**Comment by AlbertoGP** [comment]
This might actually be a shortcoming in `GLFW` because wayland support is not yet finished.

**Comment by AlbertoGP** [comment]
After some research, it turns out that this has nothing to do with Chimera.

It seems that libraries like `GLFW`, `raylib`, `sokol`, are not a good fit for `wayland` as discussed in this PR about adding wayland support to sokol: https://github.com/floooh/sokol/pull/425#issuecomment-1576533124

For me the solution is to install `xwayland`, `xserver-org-cevel`. `libxcursor-devel-static`, `libxinerama-devel-static`.

What I’m trying to do is to compile one of my programs that uses raylib without installing xorg on Chimera, that is with as few customizations as possible.

**Comment by q66** [comment]
wayland-protocols is the only protocols package, it does not need a separate -devel

glfw can be compiled with wayland, but it's either one or the other backend (i.e. you can't have support for both x11 and wayland in one library), dunno about the others

**Comment by nekopsykose** [comment]
> glfw can be compiled with wayland, but it's either one or the other backend (i.e. you can't have support for both x11 and wayland in one library)  

(next release of glfw will also fix that, current master can have both at once)
