### ISSUE TITLE
[Question] Is there gas or similar assembler available ?

### ISSUE THREAD

**Issue by sidkshatriya** [chimera-linux/cports#582]
I'm trying to compile a program on chimera and it complains that it needs an assembler `as`. I'm guessing it needs something like a gnu assembler which I don't think is available in chimera. Is there something like gas or equivalent provided by llvm toolchain available in chimera ?

**Comment by nekopsykose** [comment]
there's no `as` from binutils (gas), no. for some things, using `clang -c` aliased to `as` worked for me, but most things don't. i don't think there would be an issue with building binutils then throwing away everything except for gas in a technical sense for these cases, but @q66 might have other ideas :p

**Comment by sidkshatriya** [comment]
Yes, I too tried `clang -c` but it doesn't seem to work for me.

```
#!/bin/sh
exec clang -c "$@"
```
(I named the above `as` )

Yeah, building `binutils` is a good idea if only for `gas` -- I haven't tried it out -- does it build out of the box without patches ?

**Comment by nekopsykose** [comment]
yes, just `--disable-gprofng` is needed. you'll then see it in `./gas/as-new`. i didn't check if it actually works but it looks like it would

**Comment by sidkshatriya** [comment]
BTW An easy way to get an arbitrary package is to install `nix` package manager on your chimera distribution. As nix provides the _whole_ dependency graph for every package it is easy to get any package like binutils etc. that may not be available in chimera. I tried it out and it worked well for me.
