### ISSUE TITLE
reuse chroot /tmp

### ISSUE THREAD

**Issue by nekopsykose** [chimera-linux/cports#593]
currently, every `self.do` gets a fresh `'--tmpfs', '/tmp'`. this means doing one self.do command that outputs something to /tmp and then trying to read the output file/state/whatever from a second self.do invocation won't work. one way to work around this is to just ignore /tmp for temporary files, but that feels a bit messy when tmp is generally where one would put it..

**Comment by q66** [comment]
i don't see any way to do that, any tmpfs mount is limited by bwrap invocation, i don't think there is a way to persist it

**Comment by nekopsykose** [comment]
> any tmpfs mount is limited by bwrap invocation

do you mean a mount of a `tmpfs` filesystem specifically? merely removing that --tmpfs argument will have a dirty persistent /tmp inside the bldroot forever between all invocations, but that's of course not ideal between builds, so we would have to manage cleaning it up separately..

**Comment by q66** [comment]
i'd prefer to keep /tmp an actual tmpfs for builds, besides, you can't just remove it, the whole bldroot is read-only

**Comment by q66** [comment]
imo this is a niche enough issue that it does not really need addressing, you can always put your persistent data somewhere in builddir where they really belong

**Comment by nekopsykose** [comment]
> i'd prefer to keep /tmp an actual tmpfs for builds 

same same. guess we can keep it unfixed then

> you can't just remove it, the whole bldroot is read-only

is it? cbuild can theoretically delete whatever it wants from there at any point (later), etc (just curious)

> you can always put your persistent data somewhere in builddir where they really belong (and undergo proper cleanup by default)

yeah, settled for that, was mostly just surprising that something i wrote to a tmpfile (using TemporaryDirectory at the time) dissappeared between the self.do calls and it took me forever to actually figure out why it was not in the 'same tmp' (outside self.do it creates it on host), and then later writing to /tmp directly vanished between calls, then i realised it was this.. fine for me, but someone might run into it later too and wonder why every .do is a new bwrap invocation

**Comment by q66** [comment]
cbuild can of course, but stuff running *inside* the container can't (it's mounted as ro for any bwrap invocation)

**Comment by q66** [comment]
if you use a python tmpfile to write something in /tmp of the bldroot, bwrap invocations won't see it mostly because they will overlay that /tmp directory with a tmpfs, in general templates should not be touching any paths inside bldroot that are not in the respective builddir or destdir
