### ISSUE TITLE
scanf() causes printf() without newline ending to not execute

### ISSUE THREAD

**Issue by JamiKettunen** [chimera-linux/cports#643]
As I'm not sure whose bug this is let's have a downstream one for now at least; basically the following C program:
```c
#include <stdio.h>

int main(void) {
  int a;

  printf("a = ");
  scanf("%d", &a);

  return 0;
}
```
when compiled only only asks for input without any text (`a = `) being printed.

Adding `\n` to `printf()` call it works as expected while `strace` shows without it doesn't even call `writev()`

Dropping `scanf()` it also prints fine even without `\n`

**Comment by nekopsykose** [comment]
you forgot to flush stdout after writing to it (https://www.openwall.com/lists/musl/2016/02/10/6 , etc)

**Comment by nekopsykose** [comment]
specifically:  

>Adding \n to printf() call it works as expected  

because it's line-buffered so a newline character makes it flush instantly  

>Dropping scanf() it also prints fine even without \n  

because it also flushes when the program ends, and in that case it goes straight to the end and prints the rest

**Comment by nekopsykose** [comment]
the relevant paragraph from above:  

>Also, ISO C permitted and even encouraged (but made optional) a
behavior whereby attempting to read from a line-buffered input stream
causes all line-buffered output streams to be flushed. While this is
convenient for programmers who write prompt strings not ending in
newlines, and who don't want to be bothered with calling fflush, this
feature was conceived in an era where C did not have multi-threading,
and providing it when you have threads imposes a heavy synchronization
burden and can even lead to deadlock. Therefore musl does not do it.
So if you want to print prompt strings that don't end in a newline,
and have them appear before input is read, you have to use fflush
yourself.

**Comment by JamiKettunen** [comment]
Hm alright looks like there's nothing to do here then
