### ISSUE TITLE
eudev is needed for VM's userland start (x86_64)

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#69]
console output from x86_64:
![image](https://user-images.githubusercontent.com/12870617/145714890-4e8b4d40-4f34-42c8-9859-23c0d258b393.png)

This error disapeared once `eudev` package installed within VM and VM restarted:
```
(vm single) # apk add eudev
(vm single) # reboot
```

VM disk's image was populated thanks to the following commands:
```
$ # mount /dev/sda1 of VM disk image onto  /build/chimera/tmp/disk_mnt

$ sudo ~/chimera/bootstrap-chimera.git/chimera-bootstrap.py \
           -r /build/chimera/packages \
           -k etc/keys/yopito-60e18006.rsa.pub \
          -e neofetch /build/chimera/tmp/disk_mnt
```
So I think that `eudev` should be added as dep of `main/base-full`

**Comment by q66** [comment]
should be a dep of dinit-chimera for the time being, eventually we could theoretically make it optional (if alternative ways become possible)
