### ISSUE TITLE
missing initrd file for kernel (x86_64)

### ISSUE THREAD

**Issue by yopito** [chimera-linux/cports#70]
install grub and kernel this way in a qemu VM:
![image](https://user-images.githubusercontent.com/12870617/145814289-33ee77f5-2a97-402b-a7c5-2853e4c37ebe.png)

once rebooted, grub launches nicely booting linux kernel fails.
=> `initrd` directive is missing in corresponding grub entry ... because no `/boot/*.img` file is present on disk, corresponding to linux kernel ?

![image](https://user-images.githubusercontent.com/12870617/145814814-74e38d94-c2f4-4cfc-955e-239112a031f6.png)

**Comment by yopito** [comment]
actual `/boot` content:
![image](https://user-images.githubusercontent.com/12870617/145815177-52086ecd-4552-4506-99e3-d6a3582dc1a3.png)

**Comment by q66** [comment]
missing initramfs-tools?

**Comment by yopito** [comment]
yes, it was missing. do you have a way to trigger kernel hook for grub if linux package is already installed ?

**Comment by q66** [comment]
anyway, not a bug
