### ISSUE TITLE
target chroot should start in wrksrc

### ISSUE THREAD

**Issue by nekopsykose** [chimera-linux/cports#704]
./cbuild chroot starts in /tmp. but when ./cbuild chroot x/y, it also does, but could start in wrksrc of package too for convenience.

**Comment by q66** [comment]
there is no such thing as "target chroot", chroot command is not connected to any package or build

such behavior would be misleading as it would imply one is allowed to safely mess with a package's build from such chroot (which is not the case, as the chroot is not aware of the build stages and does nothing to set up the environment and so on, doing so would also require running the init_ hooks and such to be correct)

**Comment by nekopsykose** [comment]
> as it would imply one is allowed to safely mess with a package's build from such chroot  

hm, i dunno. i know you can't do that, and the ability to chroot at all is merely a convenience to be able to manually try things (e.g. figure out the magic test invocation, but iteratively in a shell instead of constantly rerunning do_check with misc changed, ..) in the same chrooted env the real packaging steps run in. i'm not sure how it would imply that it's something that allows tinkering with current state for packaging.

> the chroot is not aware of the build stages and does nothing to set up the environment and so on

yeah, the init_ hooks can change the directory for any individual step, and being on a step and chrooting at that point would appear to be in "another" folder. but i guess that's ok? i was thinking not 'current step wrksrc', but just the default one (/builddir/pkg-ver/). that one doesn't need any state to reach afaict. it's the equivalent of one `cd` (and so just a convenience)

**Comment by q66** [comment]
a684973cdc0c0b5156213e28795fa088557828e3, yw :)
