### ISSUE TITLE
[Feature Request] Allow subpackages to compile with `build_style`s

### ISSUE THREAD

**Issue by Froggo8311** [chimera-linux/cports#712]
The use case for this would be a package that has multiple independent makefiles in separate directories. This would allow for compiling each package separately without having to create multiple templates for the same repository.

**Comment by nekopsykose** [comment]
subpackages don't compile anything, they only steal files from pkgdir. build_styles are just thin wrappers around the default do_build/do_check/do_install/do_configure. what you're asking for is probably to run make+install in multiple directories, and you can already do that by defining do_build/... yourself, and importing things from cbuild.util like the build styles themselves do.

if that sounds like not what you're talking about, write a code (tmpl) example of what you expect to be possible that isn't currently

**Comment by nekopsykose** [comment]
contrived example:  

```
self.make.build(wrksrc="dir1")
self.make.build(wrksrc="dir2")
[...]
self.make.install(wrksrc="dir1")
self.make.install(wrksrc="dir2")
```

etc. not something that needs changing in itself, and not related to what a buildstyle does

**Comment by q66** [comment]
yeah, not an issue
