### ISSUE TITLE
Possible to become "stuck" with a broken archive for cbuild source

### ISSUE THREAD

**Issue by JamiKettunen** [chimera-linux/cports#828]
I've seen this a few times before but decided to finally write down something concrete: say for example one sets an incorrect `source` on accident like `https://invent.kde.org/frameworks/layer-shell-qt/-/archive/1573a89aac51f4efd99bdc7efda8071642291d35.tar.gz` instead of the correct `https://invent.kde.org/plasma/layer-shell-qt/-/archive/1573a89aac51f4efd99bdc7efda8071642291d35.tar.gz`, when you `./cbuild prepare-upgrade` to fill in the checksum of the downloaded 9k HTML document and upon next `./cbuild pkg` will complain similar to:
```
=> layer-shell-qt-5.27.80_git20230926-r0: running do_extract hook: 000_sources...
tar: Error opening archive: Unrecognized archive format
=> layer-shell-qt-5.27.80_git20230926-r0: ERROR: extracting '1573a89aac51f4efd99bdc7efda8071642291d35.tar.gz' failed (missing program?)
```

Easy mistake, I would've expected to be on my way after fixing `source`, `./cbuild prepare-upgrade` and `./cbuild pkg` but that's not what happens currently; instead after those the checksum was not updated and it tries the same "broken archive"

The "fun" part is even if I `rm -rf sources/layer-shell-qt-5.27.80_git20230926` and `./cbuild prepare-upgrade` again it still won't update the checksum as it seems to keep using/downloading the same old file which I already changed the `source` for in the template.

The trick to workaround this currently is to e.g. blank out `sha256` before `./cbuild prepare-upgrade`, then it actually redownloads the right file.

**Comment by q66** [comment]
i don't see how that's an issue or how one would "fix" that

as far as cbuild is concerned, you have a file+checksum pair already, fixing source does not change the filename, and the checksum matches the file, so prepare-upgrade has nothing to fix there

if you rm -rf the file in sources/, it will re-link it from by_sha256 preferentially (instead of attempting a download)

**Comment by JamiKettunen** [comment]
Hm yeah I guess the only way to deal with this properly would be to have the downloaded files be dependent on the URL and not just filename, oh well guess I'll get used to clearing the `sha256` sum in case I mess up and/or change `source` without downloaded filename changing.
