### ISSUE TITLE
fish as login shell: stty iutf8: "illegal option"

### ISSUE THREAD

**Issue by flukeeey** [chimera-linux/cports#919]
When using fish as a login shell, it calls `/usr/bin/unicode_start` in the `kbd` package as part of its default startup config (`/usr/share/fish/config.fish`, line 202), which in turn calls `stty iutf8`.

The stty command from chimerautils doesn't seem to support `stty iutf8`.

I'm not sure if this is a big problem, nothing seems to be adversely affected, so maybe I can safely ignore this error?

**Comment by q66** [comment]
probably trivial to implement

**Comment by q66** [comment]
actually no need to implement, already done in freebsd 14

**Comment by sidkshatriya** [comment]
Thanks for fixing this -- I too use fish as a login shell.

However, the warning is gone but now I receive this:

```
...
...
[  OK  ] polkitd
[  OK  ] elogind

Chimera 6.5.9-0-generic (chimera) (console)

chimera login: abcxyz
Password: 
turnstiled: srv: died without notifying readiness
Couldn't get a file descriptor referring to the console.
Welcome to fish, the friendly interactive shell
Type help for instructions on how to use fish
abczyz@chimera ~> turnstiled: srv: died without notifying readiness
turnstiled: srv: died without notifying readiness
...
```

Here I'm running agetty on ttyS0. The console is usable though. I've not investigated why the tunstiled messages are occuring.

**Comment by q66** [comment]
apologies, it seems the changes in cat broke something, so i pushed a hotfix until i figure it out

**Comment by q66** [comment]
fixed properly now
