### ISSUE TITLE
 [RFC] generic aarch64 kernel with 16K page size

### ISSUE THREAD

**Issue by dkwo** [chimera-linux/cports#940]
Useful for ARM platforms optimized to prefer operating with a 16k page size.
The Asahi Linux https://asahilinux.org/ kernel can do the job, as well as support the Apple Silicon platforms.

Would a PR for this be welcome?

**Comment by q66** [comment]
we won't be shipping a generic kernel with 16k page size

**Comment by richfelker** [comment]
Chiming in from the musl side, musl strongly prefers **not** having oversized pages (pages >4k). While mallocng's algorithms work independently of page size, the properties of avoiding serious over-allocation are stressed with poor page granularity, and these configurations are not really tested to perform well. Likewise, the memory overhead per shared library jumps from a typical 8k per library to 32k per library with 16k pages.

The hype for 16k or larger pages is really misguided. If page table/TLB overhead is really causing a performance issue for giant-data loads, the right solution is the x86 one: transparent huge pages. Not reducing the baseline memory mapping/protection granularity.

**Comment by q66** [comment]
primarily in this case there is no point in shipping a generic 16k kernel; most devices won't see any benefit from it, those that *might* see a benefit can't use a generic kernel, and yeah, in general hugepages are the answer for stuff that benefits from them (not necessarily transparent ones, but but with `madvise(..., MADV_HUGEPAGE)`, or explicitly allocated hugepage backings)

**Comment by dkwo** [comment]
Thanks, this is very informative.

@q66 Is a kernel specific to Apple silicon (with 16k page size) also out of discussion?

**Comment by q66** [comment]
not entirely out of question, but last time I checked (which was yesterday) it needed a special separate version of rust, which i consider a major blocker

**Comment by sidkshatriya** [comment]
> it needed a special separate version of rust

Asahi Linux works with a normal `aarch64-unknown-linux-gnu` rust toolchain obtained via rustup. Maybe I'm misunderstanding the point ?

Chimera on Apple Silicon (using the Asahi foundations) would be a great combination. Yes, 16K pages are used in Asahi.

Additionally, Chimera doesn't use the default musl allocator anyways -- it uses llvm's scudo -- so the issues mentioned above regarding 16K pages may not apply.

**Comment by dkwo** [comment]
Perhaps @q66 is referring to this kind of warnings (this is from alpine linux build log):
```
***
*** Rust compiler 'rustc' is too new. This may or may not work.
***   Your version:     1.72.1
1.72.1
***   Expected version: 1.68.2
***
***
*** Rust bindings generator 'bindgen' is too new. This may or may not work.
***   Your version:     0.66.1
***   Expected version: 0.56.0
***
```
My understanding is that asahi linux people are aware of this, and it should not be a problem, maybe @marcan can comment.
(A separate mesa version is still required though, until they upstream the gpu stuff.)

**Comment by q66** [comment]
as far as i can tell, whenever upstream kernel bumps up the version it comes with a large amount of adjustments to accommodate such version, and currently this fork calls for 1.66: https://github.com/AsahiLinux/linux/blob/asahi/scripts/min-tool-version.sh#L29

unless they can guarantee stuff will not break with a newer toolchain, which as far as i can tell they can't (we update the toolchain typically on the day it releases, or very shortly after), this is a no go (i'm not going to have what is essentially a vendor kernel hold back updates of either project)

**Comment by q66** [comment]
obtaining toolchains through rustup does not work and likely is never going to work on chimera (due to compiler-rt), and it wouldn't be viable for packaging regardless, and bootstrapping rustc is already pain enough as it is, adding another version that is typically several versions behind the primary one is a non-option even if i disregard my personal disdain/philosophical objections to how all this stuff works

**Comment by sidkshatriya** [comment]
_Maybe it should be possible to get this to work ?_ 

0. **Install `libgcc-chimera`** . This installs the `libgcc_s.so` shim

2. **Install the static executable version of rustup**. See https://rust-lang.github.io/rustup/installation/other.html 

   So here you would need to choose x86_64-unknown-linux-musl or aarch64-unknown-linux-musl

3. **Run rustup, it will install the musl version of the rust toolchain**

4. Notice that when you run `rustc` etc. this works on chimera because rustup provides you with a statically compiled rustc, cargo etc. Using `rustup` you can further install an arbitrary version of the rust toolchain.

5. **The rust compiler runs properly on chimera !** The only issue is that when it tries to link _your executable_ you get the following error:

```
...
...
 = note: ld: error: unable to find library -lgcc_s
          cc: error: linker command failed with exit code 1 (use -v to see invocation)
```

Here I'm a bit confused about the linker not finding libgcc_s as we already installed it in step 0. @q66 ?

**Comment by q66** [comment]
libgcc-chimera is strictly for binary compatibility, not for linking

and i will make no concessions regarding shipping packages compiled with third party toolchains, outside of bootstrapping

**Comment by sidkshatriya** [comment]
@q66 BTW the last problem can be solved by symlinking

```
$ doas ln -s /usr/lib/libgcc_s.so.1 /usr/lib/libgcc_s.so
```

**So rustup works -- I checked that it compiles a functional not trivial rust crate !!** 

Can you explain why libgcc-chimera is not for linking ?

**Comment by sidkshatriya** [comment]
@q66 (as mentioned above by using the symlink workaround, I was finally able to get the rustup obtained rust compiler generate proper binaries on chimera !! I'm guessing `libgcc-chimera` currently deliberately does not generate the `libgcc_s.so` -> `libgcc_s.so.1` symlink ).

_I do feel that allowing linking against the `libgcc_s.so` chimera shim is worthy of an exception._ 

The interface of `libgcc_s.so` would most likely be remarkably stable. Its implementation via compiler-rt would also be extremely robust. Allowing this just makes chimera more general purpose.

I for one use rust a lot. Having a functional `rustup` on chimera which allows users to switch between compiler versions and add various rust components would also be very useful. Moreover many rust projects are pinned to a particular version of the compiler for various reasons and so forth.

**Comment by q66** [comment]
this is not supported and will not be supported, no matter how "functional" the symlink hack seems, it does not provide the complete ABI and deliberately simplifies it to avoid platform-specific hacks, binaries linked with it are not ABI-compatible with binaries linked to standard gcc_s, and it is purely and only a binary compatibility shim

and rustup is not supported and will not be supported, the official binaries for musl are junk and do wrong stuff, which is all mitigated by the patchset in cports

unpatched rust compilers are not supported, and will remain not supported as long as the patchset exists

**Comment by dkwo** [comment]
@q66 makes sense.
there's also the option to not build any gpu stuff (until this gets fixed), in which case there's no rust discussion.

**Comment by sidkshatriya** [comment]
> 

> the official binaries for musl are junk and do wrong stuff, which is all mitigated by the patchset in cports (this is not even unique to chimera; alpine likewise runs into upstream rustc by default being terrible)

You probably have a lot on your plate but might it be a good idea to try upstreaming these patches to the rust project ? Long term it might be interesting to add chimera as a target to the rust project. A pure clang based distribution without even libgcc_s should be appealing to the rust maintainers.

**Comment by sidkshatriya** [comment]
> https://www.phoronix.com/review/aarch64-64k-kernel-perf

The above phoronix article is about 64K page size performance but this issue is about 16K. But yes, performance may improve in 16K page size compared to 4K if that is what you were implying

**Comment by dkwo** [comment]
Btw, since v6.11, the kernel supports a minimum version of Rust, starting with Rust 1.78.0.
