### ISSUE TITLE
suggestion: better tool for initrd

### ISSUE THREAD

**Issue by imxade** [chimera-linux/cports#98]
I noticed that chimera currently uses **[initramfs-tools](https://salsa.debian.org/kernel-team/initramfs-tools)** to generate initramfs, but I couldn't find any **LICENCE** in that repo

my suggestions :
- for now **dracut** : a mature & portable option
- for future **[tinyramfs](https://github.com/illiliti/tinyramfs)** : not mature, but most portable & offers features that would complement the idea behind chimera

**Comment by q66** [comment]
no

dracut is garbage (increasingly dependent on systemd, hostile upstream, hard bash dependency, bigger, actually less portable, worse code)

tinyramfs is written by a suckless dumbass and I'm not gonna deal with these people

there is nothing wrong with initramfs-tools, it's clean, simple, reasonably portable and backed by 30 years of development

its license is gpl-2.0-or-later https://metadata.ftp-master.debian.org/changelogs//main/i/initramfs-tools/initramfs-tools_0.142_copyright
